### PR TITLE
Mention an "is_valid" bit can save work

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Would you say that there should also be a `string.is_valid <enc>` instruction for let's say the check at the boundary to utilize, so it can skip sanitization respectively the engine can set and cache the bit for later if it has to check?

**Comment by dcodeIO** [comment]
Might also be worth to note which operations or implicit steps, like re-encoding being triggered, can set the bit as a side effect. What do you think of making a new category at the bottom mentioning potential optimizations?

**Comment by kripken** [comment]
I don't have a sense for whether checking the encoding by the wasm itself would be useful or not. Checking if the JVM and CLR have that may be interesting to do (or I guess they assume validity? then checking JS).

I'm not sure it's worth getting into much more detail on optimizations? But that may be because I think getting running code is more important :wink:

**Comment by MaxGraey** [comment]
@dcodeIO I don't think `string.is_valid <enc>`command can be useful for wasm. This valid bit probably should be just one minor implementation detail which could speed-up string validation inside VM.

**Comment by dcodeIO** [comment]
Alright, added it to the document for further discussion, if that time ever comes :) Thanks!

**Pull request closed without merging**
